version: "3.8"

services:

  app:
    image: node:12-alpine
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "${PORT:-80}:3000"
      - "${DEV_PORT:-10000}:10000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      PORT: 3000
    working_dir: /app
    command: npm run dev
